### ISSUE TITLE
Lecture 1 EBM notebook doesn't show EBM Feature Plots

### ISSUE THREAD

**Issue by cbetterley** [jphall663/GWU_rml#1]
Hi @jphall663, some of the outputs in the [Lecture 1 EBM Example notebook](https://github.com/jphall663/GWU_rml/blob/master/lecture_1_ebm_example.ipynb) do not show up properly.  It would be great to see this output to better understand the content.

Where: After cell 9 of the [Lecture 1 EBM Example notebook](https://gith.ub.com/jphall663/GWU_rml/blob/master/lecture_1_ebm_example.ipynb).  This cell includes:

```
ebm_global = ebm.explain_global(name='EBM')
show(ebm_global)
```

Error: In nbviewer, I see the following error where the plots should be:  `127.0.0.1 refused to connect`.

Thanks!

**Comment by jphall663** [comment]
Thanks for feedback and issue #1! 

I added some code to make the plots manually, which is what I prefer anyway. All these libraries are cool, but they all have little (or big) snags like this. There's probably some way to mess with Javascript or HTML to make this render ... but idk.

**Comment by jphall663** [comment]
it's here: https://github.com/jphall663/GWU_rml/blob/master/lecture_1_ebm_example.ipynb, and now there are other examples in the assignment 2 template as well: https://github.com/jphall663/GWU_rml/blob/master/assignments/assignment_2/assign_2_template.ipynb.
